# Generated by Django 4.0.2 on 2022-02-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizen', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loghash',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
